kind: pipeline
type: kubernetes
name: default
steps:
- name: build
  image: golang:alpine
  commands:
    - "go build -o ./main"
- name: publish
  image: plugins/docker
  settings:
   repo: bybys123/woof
   tags: latest
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password