  
kind: pipeline
type: kubernetes
name: default
steps:
- name: build
  image: golang:alpine
  commands:
    - "go build -o ./main"

- name: publish
  image: plugins/docker
  settings:
   repo: huhfoo/woof
   tags: latest
   username:
    from_secret: docker_username
   password:
    from_secret: docker_password

- name: deploy
  image: huhfoo/drone-kubectl
  settings:
   kubernetes_server:
    from_secret: k8s_server
   kubernetes_cert:
    from_secret: k8s_cert
   kubernetes_token:
    from_secret: k8s_token
  commands:
    - kubectl apply -f pod.yaml
    - kubectl apply -f service.yaml
    - kubectl apply -f ingress.yaml
