apiVersion: v1
kind: Service
metadata:
  name: woof-web-svc
  namespace: default
  labels:
        app: woof-web
spec:
  selector:
    app: woof-web
    type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      
