name: Sveltefire Package

on:
  push:
    paths:
      - '**.go'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          files: "etc/terraform/**"
  test:
    runs-on: ubuntu-latest
    needs: changed-files
    if: outputs.changed-files.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello"
