name: Sveltefire Package

on:
  push:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_non_terraform_changed: ${{ steps.changed-files.outputs.any_non_terraform_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          files: "!etc/terraform/**"

  cypress:
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.any_non_terraform_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"

  run-after:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello222"
