name: Custom Workflow

on: [push, pull_request]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      only_terraform_changed: ${{ steps.evaluate_changes.outputs.only_terraform_changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Check Terraform files changes
        uses: tj-actions/changed-files@v35
        id: terraform_files
        with:
          files: "/etc/terraform"

      - name: Check all files changes
        uses: tj-actions/changed-files@v35
        id: all_files
        with:
          files: "**/*"

      - name: Evaluate changes
        id: evaluate_changes
        run: |
          all_changed=${{ steps.terraform_files.outputs.all_changed }}
          any_changed=${{ steps.all_files.outputs.any_changed }}
          if [[ $all_changed == 'true' && $any_changed == 'false' ]]; then
            echo "only_terraform_changed=true" >> $GITHUB_ENV
          else
            echo "only_terraform_changed=false" >> $GITHUB_ENV
          fi

  test_job:
    needs: check_changes
    if: needs.check_changes.outputs.only_terraform_changed == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add the commands to run your tests here.
